[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[theme]
base = "light"
primaryColor = "#087f5b"
backgroundColor = "#f4f7f6"
secondaryBackgroundColor = "#ffffff"
textColor = "#171a1f"
font = "sans serif"
